language: node_js
node_js:
  - "6"
cache: yarn
env:
  - BASE_HREF=/angularjs-to-angular-presentation/
script: yarn build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master
